In [33]:
from enum import Enum

import numpy as np

from udacidrone import Drone
from udacidrone.connection import MavlinkConnection, WebSocketConnection  # noqa: F401
from udacidrone.messaging import MsgID
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
import math
from time import sleep

In [2]:
host = 'tcp:127.0.0.1'
port = 5760

In [50]:
conn = MavlinkConnection(f'{host}:{port}', threaded=True)

In [51]:
drone = Drone(conn)
drone.start()

Logs\TLog.txt


In [52]:
drone.take_control()
drone.arm()
drone.set_home_position(*drone.global_position)

In [53]:
drone.global_home

array([-122.3957519,   37.7932815,    0.       ])

In [54]:
drone.takeoff(5)

In [56]:
drone.global_position

array([-122.3957547,   37.7932814,    4.987    ])

In [57]:
drone.global_home

array([-122.3957519,   37.7932815,    0.       ])

In [58]:
drone.cmd_position(7, 0, 5, 1)

In [60]:
drone.global_home
drone.local_position
drone.global_position

array([-122.3957519,   37.7932815,    0.       ])

array([ 6.96644735,  0.0265469 , -5.00163889])

array([-122.3957516,   37.7933442,    5.001    ])

In [31]:
points = [(7, 0, 5, 0), (7, 7, 5, 0), (0, 7, 5, 0), (0, 0, 5, 0)]

In [34]:
for point in points:
    drone.cmd_position(*point)
    sleep(1)

In [35]:
drone.cmd_position(0, 0, 0.1, 0)

In [48]:
drone.land()

In [61]:
drone.disarm()
drone.release_control()
drone.stop()

Closing connection ...
